### ISSUE TITLE
Can't use Nuxt Composables

### ISSUE THREAD

**Issue by jamespatrick91** [storybook-vue/storybook-nuxt#60] opened 2023-09-13 01:25 UTC
So I'm trying to use nuxt composables like useRuntimeConfig() but then I'm getting the below error:

[nuxt] instance unavailable
Error: [nuxt] instance unavailable
    at useNuxtApp (http://localhost:6006/node_modules/nuxt/dist/app/nuxt.js?v=55bb19df:172:13)

How do we go about passing the nuxt context?

**Comment by chakAs3** [comment] 2023-09-13 01:46
please create a reproduction repo for me so i can check it out!

**Comment by peteromano** [comment] 2023-09-13 16:24
Make sure you're using nuxt composable only in <script setup>

I think there's an open issue about this changing/breaking in nuxt 3.7

**Comment by tobiasdiez** [comment] 2024-06-01 04:59
Duplicate of https://github.com/storybook-vue/storybook-nuxt/issues/97

(reproduction at https://github.com/nuxt-modules/storybook/pull/619)

**Closed by tobiasdiez** 2024-06-01 04:59 UTC
