### ISSUE TITLE
Errors for globals nuxt components

### ISSUE THREAD

**Issue by VegasChickiChicki** [storybook-vue/storybook-nuxt#37] opened 2023-08-15 17:26 UTC
Transform failed with 2 errors:                                                                                                                                                   9:20:19 PM
/Users/a1/work-projects/popso/components/global/v-button/v-button.vue:126:6: ERROR: The symbol "_hoisted_1" has already been declared
/Users/a1/work-projects/popso/components/global/v-button/v-button.vue:168:7: ERROR: Multiple exports with the same name "default"

 ERROR  Transform failed with 1 error:                                                                                                                                                    9:20:19 PM
/Users/a1/work-projects/popso/components/global/v-content-container/v-content-container.vue:56:7: ERROR: Multiple exports with the same name "default"

 ERROR  Transform failed with 2 errors:                                                                                                                                                   9:20:19 PM
/Users/a1/work-projects/popso/components/global/v-icon/v-icon.vue:48:6: ERROR: The symbol "_hoisted_1" has already been declared
/Users/a1/work-projects/popso/components/global/v-icon/v-icon.vue:71:7: ERROR: Multiple exports with the same name "default"

 ERROR  Transform failed with 2 errors:                                                                                                                                                   9:20:19 PM
/Users/a1/work-projects/popso/components/global/v-page-container/v-page-container.vue:58:6: ERROR: The symbol "_hoisted_1" has already been declared
/Users/a1/work-projects/popso/components/global/v-page-container/v-page-container.vue:93:7: ERROR: Multiple exports with the same name "default"

 ERROR  Transform failed with 1 error:                                                                                                                                                    9:20:19 PM
/Users/a1/work-projects/popso/components/global/v-text/v-text.vue:148:7: ERROR: Multiple exports with the same name "default"

 ERROR  Transform failed with 2 errors:                                                                                                                                                   9:20:19 PM
/Users/a1/work-projects/popso/components/global/v-tooltip/v-tooltip.vue:157:6: ERROR: The symbol "_hoisted_1" has already been declared
/Users/a1/work-projects/popso/components/global/v-tooltip/v-tooltip.vue:208:7: ERROR: Multiple exports with the same name "default"

### And every component that imports a global component does not work, here is such an error:

runtime.js:4 TypeError: Failed to fetch dynamically imported module: http://localhost:6006/components/ui-kit/v-error-sutb/v-error-stub.stories.js

**Comment by VegasChickiChicki** [comment] 2023-08-15 17:38
And for every global component i have error: 

 Internal server error: At least one <template> or <script> is required in a single file component.                                                                               
  Plugin: vite:vue
  File: /Users/a1/work-projects/popso/components/global/v-button/v-button.vue

**Comment by drewbaker** [comment] 2023-08-16 16:18
Think this is related: https://github.com/storybook-vue/storybook-nuxt/issues/4

**Comment by tobiasdiez** [comment] 2024-06-01 05:21
Duplicate of https://github.com/storybook-vue/storybook-nuxt/issues/4.

**Closed by tobiasdiez** 2024-06-01 05:21 UTC
