### ISSUE TITLE
Encountering '[nuxt] instance unavailable' Error When Running with 'storybook build'.

### ISSUE THREAD

**Issue by Gre212** [storybook-vue/storybook-nuxt#102] opened 2024-04-19 03:51 UTC
**Objective:**
I aim to generate static files using `npx storybook build`.

**Issue:**
Upon examining the built files, I consistently encounter the `[nuxt] instance unavailable` error.

**Commands Executed:**
```
$ npx storybook build
$ npx http-server storybook-static
```

**Additional Context:**
I can access Storybook when launching it alongside Nuxt3 using `npm run dev`.

I would greatly appreciate any guidance or insights on how to resolve this error and successfully generate static files with Storybook.

**Comment by cheyer** [comment] 2024-05-19 22:32
I am experiencing the same issue described here.
We have a story involving a menu component that uses `NuxtLink` internally. When running Storybook in development mode with `npm run storybook`, everything works perfectly, and the story renders without any issues.
However, upon building Storybook for deployment on GitHub Pages using `npm run build-storybook`, I encounter the `Error: [nuxt] instance unavailable` message for the same story.
I guess this is also related to https://github.com/storybook-vue/storybook-nuxt/issues/97

**Comment by tobiasdiez** [comment] 2024-06-01 05:00
Duplicate of https://github.com/storybook-vue/storybook-nuxt/issues/97

**Closed by tobiasdiez** 2024-06-01 05:00 UTC
